package ai.qodo.joke;


public interface Joke {
    /**
     * Generate an evil joke based on the input name.
     * @param name
     * @return the joke that is generated by AI.
     */
    String joke(String name);
}
